# Generated by Django 5.0.4 on 2024-04-15 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户表'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
