# Generated by Django 5.0.4 on 2024-04-15 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户登录信息表'},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=40, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, verbose_name='用户名'),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(null=True, verbose_name='生日')),
                ('signature', models.TextField(verbose_name='个性签名')),
                ('biography', models.TextField(verbose_name='个人简介')),
                ('school', models.CharField(max_length=50, verbose_name='所在学校')),
                ('articles', models.IntegerField(default=0, verbose_name='写的文章数')),
                ('last_login_Date', models.DateTimeField(auto_now_add=True, verbose_name='最后登录时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户名')),
            ],
            options={
                'verbose_name': '用户详细信息表',
                'db_table': 'userinfo',
            },
        ),
    ]
