# Generated by Django 5.0.4 on 2024-04-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_options_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='biography',
            field=models.TextField(default='这个家伙很懒，什么都没留下！', verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='signature',
            field=models.TextField(default='这个家伙很懒，什么都没留下！', verbose_name='个性签名'),
        ),
    ]
