# Generated by Django 5.0.6 on 2024-06-03 06:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_category_tag_alter_article_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='created_at',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='updated_at',
            new_name='update_time',
        ),
        migrations.AddField(
            model_name='article',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='删除标记'),
        ),
        migrations.AddField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='删除标记'),
        ),
        migrations.AddField(
            model_name='comment',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
