# Generated by Django 5.0.6 on 2024-06-03 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_create_time_alter_article_update_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_delete',
        ),
    ]
