# Generated by Django 5.0.6 on 2024-05-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=11, unique=True)),
                ('avatar', models.ImageField(blank=True, default='static/avatar/default.jpg', null=True, upload_to='static/avatar/')),
                ('face', models.CharField(max_length=100, verbose_name='人脸')),
            ],
            options={
                'verbose_name': '用户表',
                'db_table': 'users',
            },
        ),
    ]
