# Generated by Django 5.0.6 on 2024-05-24 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('read', models.BooleanField(default=False, verbose_name='已读')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='users.user', verbose_name='接收者')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='users.user', verbose_name='发送者')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100, verbose_name='学校')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('state', models.CharField(max_length=50, verbose_name='省份')),
                ('zip', models.CharField(max_length=10, verbose_name='邮编')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('hobbies', models.CharField(max_length=100, verbose_name='爱好')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('github', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('degree', models.CharField(max_length=50, verbose_name='学位')),
                ('major', models.CharField(max_length=50, verbose_name='专业')),
                ('graduation_year', models.IntegerField(verbose_name='毕业年份')),
                ('company_name', models.CharField(max_length=100, verbose_name='公司名称')),
                ('job_title', models.CharField(max_length=100, verbose_name='职位')),
                ('job_description', models.TextField(verbose_name='工作描述')),
                ('skills', models.CharField(max_length=200, verbose_name='技能')),
                ('certificates', models.CharField(blank=True, max_length=200, null=True, verbose_name='证书')),
                ('languages', models.CharField(max_length=100, verbose_name='语言能力')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '个人资料',
                'verbose_name_plural': '个人资料',
                'db_table': 'personal_data',
            },
        ),
    ]
