# Generated by Django 5.0.4 on 2024-04-15 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifycode',
            name='created_at',
        ),
    ]
