# Generated by Django 5.0.6 on 2024-05-28 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_message_personaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='degree',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='学位'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='毕业年份'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='hobbies',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='爱好'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='job_description',
            field=models.TextField(blank=True, null=True, verbose_name='工作描述'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='languages',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='语言能力'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='major',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='skills',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='技能'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='所属用户'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='zip',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='邮编'),
        ),
    ]
