# Generated by Django 5.0.4 on 2024-04-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='static/avatar/default.jpg', null=True, upload_to='static/avatar/'),
        ),
    ]
