# Generated by Django 5.0.6 on 2024-05-24 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_category_tag_alter_article_options_and_more'),
        ('users', '0002_message_personaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='反馈内容')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '反馈',
                'verbose_name_plural': '反馈',
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_time', models.DateTimeField(auto_now_add=True, verbose_name='审核时间')),
                ('approved', models.BooleanField(default=False, verbose_name='是否通过')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='articles.article', verbose_name='文章')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='审核人')),
            ],
            options={
                'verbose_name': '审核',
                'verbose_name_plural': '审核',
                'db_table': 'reviews',
            },
        ),
    ]
