/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Calendar: typeof import('./src/components/calendar/Calendar.vue')['default']
    Cps_Aside: typeof import('./src/components/layer/components/Cps_Aside.vue')['default']
    Cps_Header: typeof import('./src/components/layer/components/Cps_Header.vue')['default']
    EditorMD: typeof import('./src/components/editor/EditorMD.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    Face: typeof import('./src/components/face/face.vue')['default']
    FaceModal: typeof import('./src/components/face/faceModal.vue')['default']
    G_Drawer: typeof import('./src/components/drawer/g_Drawer.vue')['default']
    Layer: typeof import('./src/components/layer/Layer.vue')['default']
    LoginModal: typeof import('./src/components/loginModal/loginModal.vue')['default']
    MarkdownEditor: typeof import('./src/components/editor/MarkdownEditor.vue')['default']
    MonacoEditor: typeof import('./src/components/editor/MonacoEditor.vue')['default']
    MusicPlayer: typeof import('./src/components/MusicPlayer/MusicPlayer.vue')['default']
    RegisterModal: typeof import('./src/components/loginModal/registerModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeCard: typeof import('./src/components/TimeCard/TimeCard.vue')['default']
  }
}
